import type { CareerPath } from "./types";

/**
 * Career paths. Salary ranges are *reference estimates* compiled from public
 * market data (US BLS 2024 median DS = $112,590) and typical Vietnam IT bands.
 * Treat them as ballparks, not guarantees.
 */
export const CAREERS: CareerPath[] = [
  {
    id: "data-analyst",
    name: "Data Analyst",
    icon: "BarChart3",
    color: "amber",
    question: "What happened, and why?",
    tagline: "Looks at the past — turns data into dashboards & decisions.",
    prioritySkills: [
      "Strong SQL",
      "pandas",
      "Visualization",
      "Descriptive statistics",
      "A/B testing",
      "Power BI / Tableau",
    ],
    later: ["dbt fundamentals", "Modern analytics stack"],
    skip: ["Deep learning", "Heavy cloud", "Advanced MLOps"],
    keySkill: "Strong SQL + storytelling with data",
    portfolio: "2 analytics dashboards + 1 A/B-testing case + 1 SQL-heavy project",
    recommendedProjects: ["pr1", "pr2"],
    estimatedTime: "6-9 months",
    salary: {
      vnJunior: "₫12–20M / mo",
      vnMid: "₫25–40M / mo",
      globalUsd: "$60K–$90K / yr",
      note: "The most accessible entry point for career changers.",
    },
    courseIds: ["ucdavis-sql", "kaggle-pandas", "powerbi", "tableau", "dbt"],
  },
  {
    id: "data-scientist",
    name: "Data Scientist",
    icon: "Microscope",
    color: "blue",
    question: "What will happen? What should we do?",
    tagline: "Looks ahead — predictive models, experiments, statistics.",
    prioritySkills: [
      "Deep statistics",
      "Full classic ML",
      "Feature engineering",
      "Model evaluation",
      "Experiment design",
    ],
    later: ["Deep learning", "Advanced time series", "Causal inference"],
    skip: ["Deep BI tools", "Heavy infra/cloud"],
    keySkill: "Honest model evaluation + experiment design + communicating results",
    portfolio: "1 full ML project + 1 experiment/stats project + 1 domain project",
    recommendedProjects: ["pr3", "pr4"],
    estimatedTime: "9-12 months",
    salary: {
      vnJunior: "₫18–30M / mo",
      vnMid: "₫35–60M / mo",
      globalUsd: "$112K / yr (US median, BLS 2024)",
      note: "US median Data Scientist salary in 2024 was $112,590/yr (BLS).",
    },
    courseIds: ["ng-ml", "islp", "google-mlcc", "kaggle-ml", "mit-1805"],
  },
  {
    id: "ml-engineer",
    name: "ML Engineer",
    icon: "Cog",
    color: "emerald",
    question: "How do we run models reliably in production?",
    tagline: "Owns the engineering/ops — package, deploy, monitor models.",
    prioritySkills: [
      "Python + software engineering",
      "scikit-learn",
      "FastAPI",
      "Docker",
      "MLflow",
      "One cloud provider",
    ],
    later: ["DVC", "Orchestration", "Managed ML", "Monitoring"],
    skip: ["R", "BI tools", "Theory beyond what you can ship"],
    keySkill: "Package & deploy models + production mindset + clean code",
    portfolio: "1 strong ML project + 1 deployed API/app + 1 reproducible pipeline repo",
    recommendedProjects: ["pr4", "pr5"],
    estimatedTime: "9-12 months",
    salary: {
      vnJunior: "₫20–35M / mo",
      vnMid: "₫40–70M / mo",
      globalUsd: "$100K–$150K / yr",
      note: "Deploy + clean-code skills command a premium in the 2026 market.",
    },
    courseIds: ["fastapi", "docker", "mlflow", "dvc", "fsdl", "google-mle"],
  },
  {
    id: "ai-engineer",
    name: "AI Engineer",
    icon: "BrainCircuit",
    color: "pink",
    question: "How do we build products with LLMs/AI?",
    tagline: "Builds next-gen AI products — chatbots, RAG, AI agents.",
    hot: true,
    prioritySkills: [
      "LLMs & prompting",
      "RAG",
      "Vector databases",
      "AI agents",
      "API integration",
      "Software engineering",
    ],
    later: ["LangGraph", "MCP", "Fine-tuning", "LLM evaluation", "Agentic workflows"],
    skip: ["⚠️ Don't skip ML foundations! Good AI Engineers still understand ML & deployment"],
    keySkill: "Build real LLM products + evaluate quality + ground them with your own data (RAG)",
    portfolio: "1 RAG application + 1 AI agent + 1 LLM-integrated API service",
    recommendedProjects: ["pr5", "pr6"],
    estimatedTime: "12+ months (ML foundation required)",
    salary: {
      vnJunior: "₫25–40M / mo",
      vnMid: "₫50–90M / mo",
      globalUsd: "$120K–$180K / yr",
      note: "Hottest role of 2026 — but needs solid ML foundations, not just 'calling an API'.",
    },
    courseIds: ["dlai-short", "langgraph", "mcp", "hf-llm", "aws-ml"],
  },
  {
    id: "applied-scientist",
    name: "Applied Scientist",
    icon: "FlaskConical",
    color: "purple",
    question: "How do we turn research into impactful products?",
    tagline: "Research × engineering hybrid — often needs an MSc/PhD.",
    prioritySkills: [
      "Deep math & statistics",
      "Deep learning",
      "Reading & reproducing papers",
      "Rigorous experimentation",
      "Software engineering",
    ],
    later: ["Research publications", "Deep specialization (NLP/CV/RL)"],
    skip: ["BI tools", "Heavy dashboards"],
    keySkill: "Research mindset + reproducing results + bringing research to production",
    portfolio: "1 paper reproduction + 1 deep DL project + 1 open-source contribution",
    recommendedProjects: ["pr4", "pr6"],
    estimatedTime: "18+ months (often needs an advanced degree)",
    salary: {
      vnJunior: "₫30–50M / mo",
      vnMid: "₫60–120M / mo",
      globalUsd: "$140K–$220K / yr",
      note: "Research roles typically require a master's degree or higher (per BLS).",
    },
    courseIds: ["ng-dl", "fastai", "hf-learn", "mit-1806", "homl"],
  },
];

export const CAREER_BY_ID = Object.fromEntries(
  CAREERS.map((c) => [c.id, c]),
) as Record<string, CareerPath>;
