import type { CareerPath } from "./types";

/**
 * Career paths. Salary ranges are *reference estimates* compiled from public
 * market data (US BLS 2024 median DS = $112,590) and typical Vietnam IT bands.
 * Treat them as ballparks, not guarantees.
 */
export const CAREERS: CareerPath[] = [
  {
    id: "data-analyst",
    name: "Data Analyst",
    icon: "BarChart3",
    color: "amber",
    question: "Chuyện gì đã xảy ra và tại sao?",
    tagline: "Nhìn về quá khứ — biến dữ liệu thành dashboard & quyết định.",
    prioritySkills: [
      "SQL thành thạo",
      "pandas",
      "Visualization",
      "Thống kê mô tả",
      "A/B testing",
      "Power BI / Tableau",
    ],
    later: ["dbt fundamentals", "Modern analytics stack"],
    skip: ["Deep learning", "Cloud nặng", "MLOps nâng cao"],
    keySkill: "SQL thành thạo + kể chuyện bằng dữ liệu (storytelling)",
    portfolio: "2 dashboard phân tích + 1 case A/B testing + 1 project SQL-heavy",
    recommendedProjects: ["pr1", "pr2"],
    estimatedTime: "6-9 tháng",
    salary: {
      vnJunior: "12-20 triệu/tháng",
      vnMid: "25-40 triệu/tháng",
      globalUsd: "$60K-$90K/năm",
      note: "Entry point dễ tiếp cận nhất cho người mới chuyển ngành.",
    },
    courseIds: ["ucdavis-sql", "kaggle-pandas", "powerbi", "tableau", "dbt"],
  },
  {
    id: "data-scientist",
    name: "Data Scientist",
    icon: "Microscope",
    color: "blue",
    question: "Chuyện gì sẽ xảy ra? Nên làm gì?",
    tagline: "Nhìn về tương lai — mô hình dự đoán, thí nghiệm, thống kê.",
    prioritySkills: [
      "Thống kê sâu",
      "ML cổ điển đầy đủ",
      "Feature engineering",
      "Đánh giá mô hình",
      "Thiết kế thí nghiệm",
    ],
    later: ["Deep learning", "Time series nâng cao", "Causal inference"],
    skip: ["BI tools chuyên sâu", "Infra/cloud nặng"],
    keySkill: "Đánh giá mô hình trung thực + thiết kế thí nghiệm + giao tiếp kết quả",
    portfolio: "1 project ML đầy đủ + 1 project thí nghiệm/thống kê + 1 project theo lĩnh vực",
    recommendedProjects: ["pr3", "pr4"],
    estimatedTime: "9-12 tháng",
    salary: {
      vnJunior: "18-30 triệu/tháng",
      vnMid: "35-60 triệu/tháng",
      globalUsd: "$112K/năm (median, BLS 2024)",
      note: "Mỹ: lương trung vị Data Scientist 2024 là $112,590/năm (BLS).",
    },
    courseIds: ["ng-ml", "islp", "google-mlcc", "kaggle-ml", "mit-1805"],
  },
  {
    id: "ml-engineer",
    name: "ML Engineer",
    icon: "Cog",
    color: "emerald",
    question: "Làm sao đưa mô hình lên production chạy ổn định?",
    tagline: "Lo phần kỹ thuật/vận hành — đóng gói, deploy, monitor mô hình.",
    prioritySkills: [
      "Python + software engineering",
      "scikit-learn",
      "FastAPI",
      "Docker",
      "MLflow",
      "1 cloud provider",
    ],
    later: ["DVC", "Orchestration", "Managed ML", "Monitoring"],
    skip: ["R", "BI tools", "Lý thuyết sâu vượt mức triển khai được"],
    keySkill: "Đóng gói & deploy mô hình + tư duy production + clean code",
    portfolio: "1 project ML mạnh + 1 API/app đã deploy + 1 reproducible pipeline repo",
    recommendedProjects: ["pr4", "pr5"],
    estimatedTime: "9-12 tháng",
    salary: {
      vnJunior: "20-35 triệu/tháng",
      vnMid: "40-70 triệu/tháng",
      globalUsd: "$100K-$150K/năm",
      note: "Kỹ năng deploy + clean code được trả giá cao trên thị trường 2026.",
    },
    courseIds: ["fastapi", "docker", "mlflow", "dvc", "fsdl", "google-mle"],
  },
  {
    id: "ai-engineer",
    name: "AI Engineer",
    icon: "BrainCircuit",
    color: "pink",
    question: "Làm sao xây sản phẩm dùng LLM/AI?",
    tagline: "Xây sản phẩm AI thế hệ mới — chatbot, RAG, AI agent.",
    hot: true,
    prioritySkills: [
      "LLM & prompting",
      "RAG",
      "Vector database",
      "AI agents",
      "API integration",
      "Software engineering",
    ],
    later: ["LangGraph", "MCP", "Fine-tuning", "LLM evaluation", "Agentic workflows"],
    skip: ["⚠️ ĐỪNG bỏ qua nền tảng ML! AI Engineer giỏi vẫn cần hiểu ML & deployment"],
    keySkill: "Xây sản phẩm LLM thật + đánh giá chất lượng + kết hợp dữ liệu riêng (RAG)",
    portfolio: "1 ứng dụng RAG + 1 AI agent + 1 API service tích hợp LLM",
    recommendedProjects: ["pr5", "pr6"],
    estimatedTime: "12+ tháng (cần nền ML trước)",
    salary: {
      vnJunior: "25-40 triệu/tháng",
      vnMid: "50-90 triệu/tháng",
      globalUsd: "$120K-$180K/năm",
      note: "Hot nhất 2026 — nhưng cần nền tảng ML vững, không phải chỉ 'gọi API'.",
    },
    courseIds: ["dlai-short", "langgraph", "mcp", "hf-llm", "aws-ml"],
  },
  {
    id: "applied-scientist",
    name: "Applied Scientist",
    icon: "FlaskConical",
    color: "purple",
    question: "Làm sao biến nghiên cứu thành sản phẩm có tác động?",
    tagline: "Lai giữa nghiên cứu & kỹ thuật — thường yêu cầu thạc sĩ/tiến sĩ.",
    prioritySkills: [
      "Toán & thống kê sâu",
      "Deep learning",
      "Đọc & tái lập paper",
      "Thực nghiệm chặt chẽ",
      "Software engineering",
    ],
    later: ["Research publications", "Lĩnh vực chuyên sâu (NLP/CV/RL)"],
    skip: ["BI tools", "Dashboard nặng"],
    keySkill: "Tư duy nghiên cứu + tái lập kết quả + đưa research vào production",
    portfolio: "1 paper reproduction + 1 project DL chuyên sâu + 1 đóng góp open-source",
    recommendedProjects: ["pr4", "pr6"],
    estimatedTime: "18+ tháng (thường cần bằng cấp cao)",
    salary: {
      vnJunior: "30-50 triệu/tháng",
      vnMid: "60-120 triệu/tháng",
      globalUsd: "$140K-$220K/năm",
      note: "Vai trò research thường yêu cầu thạc sĩ trở lên (theo BLS).",
    },
    courseIds: ["ng-dl", "fastai", "hf-learn", "mit-1806", "homl"],
  },
];

export const CAREER_BY_ID = Object.fromEntries(
  CAREERS.map((c) => [c.id, c]),
) as Record<string, CareerPath>;
