import type { Course } from "./types";

/**
 * Curated course catalog — sourced from the 2026 Beginner Data Science Roadmap.
 * Priority order of providers: Andrew Ng → DeepLearning.AI → Stanford → Harvard
 * → MIT → Google → Kaggle → Official docs.
 */
export const COURSES: Course[] = [
  // ── Python & Programming ──
  {
    id: "cs50p",
    name: "CS50P: Intro to Programming with Python",
    provider: "Harvard",
    level: "Beginner",
    duration: "~9 tuần",
    cost: "Free",
    url: "https://pll.harvard.edu/course/cs50s-introduction-programming-python",
    category: "Python",
    tags: ["Python", "Fundamentals"],
    featured: true,
  },
  {
    id: "py-tutorial",
    name: "Python Official Tutorial",
    provider: "Python.org",
    level: "Beginner",
    duration: "Tự học",
    cost: "Free",
    url: "https://docs.python.org/3/tutorial/index.html",
    category: "Python",
    tags: ["Python", "Docs"],
  },
  {
    id: "kaggle-python",
    name: "Kaggle: Python",
    provider: "Kaggle",
    level: "Beginner",
    duration: "~5 giờ",
    cost: "Free",
    url: "https://www.kaggle.com/learn/python",
    category: "Python",
    tags: ["Python", "Hands-on"],
  },
  {
    id: "think-python",
    name: "Think Python (sách)",
    provider: "Allen Downey",
    level: "Beginner",
    duration: "Tự học",
    cost: "Free",
    url: "https://allendowney.github.io/ThinkPython/",
    category: "Python",
    tags: ["Python", "Book"],
  },
  {
    id: "pro-git",
    name: "Pro Git (sách)",
    provider: "Git-SCM",
    level: "Beginner",
    duration: "Tham khảo",
    cost: "Free",
    url: "https://git-scm.com/book/en/v2",
    category: "Python",
    tags: ["Git", "Book"],
  },

  // ── Math & Statistics ──
  {
    id: "khan-stats",
    name: "Statistics & Probability",
    provider: "Khan Academy",
    level: "Beginner",
    duration: "Tự học",
    cost: "Free",
    url: "https://www.khanacademy.org/math/statistics-probability",
    category: "Math",
    tags: ["Statistics", "Probability"],
  },
  {
    id: "openintro",
    name: "OpenIntro Statistics (sách)",
    provider: "OpenIntro",
    level: "Beginner",
    duration: "Tự học",
    cost: "Free",
    url: "https://www.openintro.org/book/os/",
    category: "Math",
    tags: ["Statistics", "Book"],
  },
  {
    id: "mit-1805",
    name: "Intro to Probability & Statistics (18.05)",
    provider: "MIT OCW",
    level: "Intermediate",
    duration: "1 học kỳ",
    cost: "Free",
    url: "https://ocw.mit.edu/courses/18-05-introduction-to-probability-and-statistics-spring-2014/",
    category: "Math",
    tags: ["Statistics", "Probability"],
    featured: true,
  },
  {
    id: "mit-1806",
    name: "Linear Algebra (18.06)",
    provider: "MIT OCW",
    level: "Intermediate",
    duration: "1 học kỳ",
    cost: "Free",
    url: "https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/",
    category: "Math",
    tags: ["Linear Algebra"],
    featured: true,
  },
  {
    id: "think-stats",
    name: "Think Stats (sách)",
    provider: "Allen Downey",
    level: "Beginner",
    duration: "Tự học",
    cost: "Free",
    url: "https://allendowney.github.io/ThinkStats/",
    category: "Math",
    tags: ["Statistics", "Book"],
  },

  // ── SQL ──
  {
    id: "pg-tutorial",
    name: "PostgreSQL Tutorial",
    provider: "PostgreSQL.org",
    level: "Beginner",
    duration: "Tự học",
    cost: "Free",
    url: "https://www.postgresql.org/docs/current/tutorial.html",
    category: "SQL",
    tags: ["SQL", "Postgres"],
  },
  {
    id: "khan-sql",
    name: "Intro to SQL",
    provider: "Khan Academy",
    level: "Beginner",
    duration: "~5 giờ",
    cost: "Free",
    url: "https://www.khanacademy.org/computing/computer-programming/sql",
    category: "SQL",
    tags: ["SQL"],
  },
  {
    id: "ucdavis-sql",
    name: "SQL for Data Science",
    provider: "UC Davis (Coursera)",
    level: "Beginner",
    duration: "~4 tuần",
    cost: "Free audit",
    url: "https://cpe.ucdavis.edu/section/sql-data-science-coursera",
    category: "SQL",
    tags: ["SQL", "Structured"],
    featured: true,
  },
  {
    id: "duckdb",
    name: "DuckDB Docs",
    provider: "DuckDB",
    level: "Intermediate",
    duration: "Tham khảo",
    cost: "Free",
    url: "https://duckdb.org/docs/current/",
    category: "SQL",
    tags: ["SQL", "Analytics"],
  },

  // ── pandas / NumPy / Viz ──
  {
    id: "pandas-start",
    name: "pandas: Getting Started",
    provider: "pandas.org",
    level: "Beginner",
    duration: "Tự học",
    cost: "Free",
    url: "https://pandas.pydata.org/docs/getting_started/index.html",
    category: "Data",
    tags: ["pandas", "Docs"],
  },
  {
    id: "kaggle-pandas",
    name: "Kaggle: Pandas",
    provider: "Kaggle",
    level: "Beginner",
    duration: "~4 giờ",
    cost: "Free",
    url: "https://www.kaggle.com/learn/pandas",
    category: "Data",
    tags: ["pandas", "Hands-on"],
  },
  {
    id: "numpy",
    name: "NumPy Quickstart",
    provider: "NumPy.org",
    level: "Beginner",
    duration: "Tự học",
    cost: "Free",
    url: "https://numpy.org/doc/stable/user/quickstart.html",
    category: "Data",
    tags: ["NumPy"],
  },
  {
    id: "matplotlib",
    name: "Matplotlib Tutorials",
    provider: "Matplotlib.org",
    level: "Beginner",
    duration: "Tự học",
    cost: "Free",
    url: "https://matplotlib.org/stable/tutorials/index.html",
    category: "Data",
    tags: ["Visualization"],
  },
  {
    id: "seaborn",
    name: "Seaborn Tutorial",
    provider: "Seaborn",
    level: "Beginner",
    duration: "Tự học",
    cost: "Free",
    url: "https://seaborn.pydata.org/tutorial.html",
    category: "Data",
    tags: ["Visualization"],
  },
  {
    id: "kaggle-viz",
    name: "Kaggle: Data Visualization",
    provider: "Kaggle",
    level: "Beginner",
    duration: "~4 giờ",
    cost: "Free",
    url: "https://www.kaggle.com/learn/data-visualization",
    category: "Data",
    tags: ["Visualization", "Hands-on"],
  },

  // ── Machine Learning ──
  {
    id: "google-mlcc",
    name: "Machine Learning Crash Course",
    provider: "Google",
    level: "Beginner",
    duration: "~15 giờ",
    cost: "Free",
    url: "https://developers.google.com/machine-learning/crash-course",
    category: "ML",
    tags: ["ML", "Fundamentals"],
    featured: true,
  },
  {
    id: "ng-ml",
    name: "Machine Learning Specialization",
    provider: "Andrew Ng / DeepLearning.AI",
    level: "Beginner",
    duration: "~2-3 tháng",
    cost: "Free audit",
    url: "https://www.coursera.org/specializations/machine-learning-introduction",
    category: "ML",
    tags: ["ML", "Specialization"],
    featured: true,
  },
  {
    id: "sklearn-start",
    name: "scikit-learn: Getting Started",
    provider: "scikit-learn",
    level: "Beginner",
    duration: "Tự học",
    cost: "Free",
    url: "https://scikit-learn.org/stable/getting_started.html",
    category: "ML",
    tags: ["scikit-learn"],
  },
  {
    id: "sklearn-model",
    name: "scikit-learn: Model Selection",
    provider: "scikit-learn",
    level: "Intermediate",
    duration: "Tham khảo",
    cost: "Free",
    url: "https://scikit-learn.org/stable/model_selection.html",
    category: "ML",
    tags: ["scikit-learn", "Evaluation"],
  },
  {
    id: "kaggle-ml",
    name: "Kaggle: Intro to ML + Intermediate ML",
    provider: "Kaggle",
    level: "Beginner",
    duration: "~7 giờ",
    cost: "Free",
    url: "https://www.kaggle.com/learn/intro-to-machine-learning",
    category: "ML",
    tags: ["ML", "Hands-on"],
  },
  {
    id: "islp",
    name: "An Introduction to Statistical Learning (sách)",
    provider: "Stanford",
    level: "Beginner",
    duration: "Tự học",
    cost: "Free",
    url: "https://www.statlearning.com/",
    category: "ML",
    tags: ["ML", "Book"],
    featured: true,
  },
  {
    id: "homl",
    name: "Hands-On Machine Learning (sách)",
    provider: "O'Reilly",
    level: "Intermediate",
    duration: "Tự học",
    cost: "Paid",
    url: "https://www.oreilly.com/library/view/hands-on-machine-learning/9781492032632/",
    category: "ML",
    tags: ["ML", "Book"],
  },

  // ── Deep Learning ──
  {
    id: "pytorch-basics",
    name: "PyTorch: Learn the Basics",
    provider: "PyTorch",
    level: "Beginner",
    duration: "~3 giờ",
    cost: "Free",
    url: "https://docs.pytorch.org/tutorials/beginner/basics/intro.html",
    category: "DL",
    tags: ["PyTorch", "Deep Learning"],
  },
  {
    id: "ng-dl",
    name: "Deep Learning Specialization",
    provider: "Andrew Ng / DeepLearning.AI",
    level: "Intermediate",
    duration: "~3 tháng",
    cost: "Free audit",
    url: "https://www.coursera.org/specializations/deep-learning",
    category: "DL",
    tags: ["Deep Learning", "Specialization"],
    featured: true,
  },
  {
    id: "fastai",
    name: "Practical Deep Learning",
    provider: "fast.ai",
    level: "Beginner",
    duration: "~7 tuần",
    cost: "Free",
    url: "https://course.fast.ai/",
    category: "DL",
    tags: ["Deep Learning"],
  },
  {
    id: "tensorflow",
    name: "TensorFlow Tutorials",
    provider: "TensorFlow",
    level: "Beginner",
    duration: "Tự học",
    cost: "Free",
    url: "https://www.tensorflow.org/tutorials",
    category: "DL",
    tags: ["TensorFlow", "Deep Learning"],
  },
  {
    id: "hf-learn",
    name: "Hugging Face Learn",
    provider: "Hugging Face",
    level: "Intermediate",
    duration: "Tự học",
    cost: "Free",
    url: "https://huggingface.co/learn",
    category: "DL",
    tags: ["NLP", "Transformers"],
  },

  // ── Responsible AI ──
  {
    id: "nist-rmf",
    name: "NIST AI Risk Management Framework",
    provider: "NIST",
    level: "Intermediate",
    duration: "Tham khảo",
    cost: "Free",
    url: "https://www.nist.gov/itl/ai-risk-management-framework",
    category: "Responsible AI",
    tags: ["Governance", "Risk"],
  },
  {
    id: "kaggle-ethics",
    name: "Kaggle: Intro to AI Ethics",
    provider: "Kaggle",
    level: "Beginner",
    duration: "~4 giờ",
    cost: "Free",
    url: "https://www.kaggle.com/learn/intro-to-ai-ethics",
    category: "Responsible AI",
    tags: ["Ethics", "Fairness"],
  },
  {
    id: "oecd-ai",
    name: "OECD AI Principles",
    provider: "OECD",
    level: "Beginner",
    duration: "Tham khảo",
    cost: "Free",
    url: "https://oecd.ai/en/ai-principles",
    category: "Responsible AI",
    tags: ["Policy", "Principles"],
  },
  {
    id: "kaggle-timeseries",
    name: "Kaggle: Time Series",
    provider: "Kaggle",
    level: "Beginner",
    duration: "~5 giờ",
    cost: "Free",
    url: "https://www.kaggle.com/learn/time-series",
    category: "ML",
    tags: ["Time Series", "Hands-on"],
  },

  // ── MLOps & Deployment ──
  {
    id: "mlflow",
    name: "MLflow Docs",
    provider: "MLflow",
    level: "Intermediate",
    duration: "Tự học",
    cost: "Free",
    url: "https://mlflow.org/docs/latest/",
    category: "MLOps",
    tags: ["MLflow", "Tracking"],
  },
  {
    id: "dvc",
    name: "DVC: Get Started",
    provider: "DVC",
    level: "Intermediate",
    duration: "Tự học",
    cost: "Free",
    url: "https://doc.dvc.org/start",
    category: "MLOps",
    tags: ["Versioning"],
  },
  {
    id: "fastapi",
    name: "FastAPI Tutorial",
    provider: "FastAPI",
    level: "Beginner",
    duration: "Tự học",
    cost: "Free",
    url: "https://fastapi.tiangolo.com/tutorial/",
    category: "MLOps",
    tags: ["API", "Serving"],
  },
  {
    id: "docker",
    name: "Docker: Get Started",
    provider: "Docker",
    level: "Beginner",
    duration: "Tự học",
    cost: "Free",
    url: "https://docs.docker.com/get-started/",
    category: "MLOps",
    tags: ["Docker", "Containers"],
  },
  {
    id: "streamlit",
    name: "Streamlit: Get Started",
    provider: "Streamlit",
    level: "Beginner",
    duration: "Tự học",
    cost: "Free",
    url: "https://docs.streamlit.io/get-started",
    category: "MLOps",
    tags: ["App", "Demo"],
  },
  {
    id: "fsdl",
    name: "Full Stack Deep Learning",
    provider: "FSDL",
    level: "Intermediate",
    duration: "Tự học",
    cost: "Free",
    url: "https://fullstackdeeplearning.com/",
    category: "MLOps",
    tags: ["MLOps", "Production"],
  },

  // ── Cloud & AI Engineering 2026 ──
  {
    id: "google-mle",
    name: "ML Engineer Path",
    provider: "Google Skills",
    level: "Intermediate",
    duration: "Tự học",
    cost: "Free audit",
    url: "https://www.skills.google/paths/17/course_templates/158",
    category: "AI 2026",
    tags: ["Cloud", "GCP"],
  },
  {
    id: "aws-ml",
    name: "AWS Skill Builder (ML)",
    provider: "AWS",
    level: "Intermediate",
    duration: "Tự học",
    cost: "Mixed",
    url: "https://skillbuilder.aws/category/role/machine-learning-engineer",
    category: "AI 2026",
    tags: ["Cloud", "AWS"],
  },
  {
    id: "azure-ds",
    name: "Azure Data Scientist",
    provider: "Microsoft Learn",
    level: "Intermediate",
    duration: "Tự học",
    cost: "Free",
    url: "https://learn.microsoft.com/en-us/training/career-paths/data-scientist",
    category: "AI 2026",
    tags: ["Cloud", "Azure"],
  },
  {
    id: "dlai-short",
    name: "DeepLearning.AI Short Courses (LLM, RAG, Agents)",
    provider: "DeepLearning.AI",
    level: "Beginner",
    duration: "~1-2 giờ/khóa",
    cost: "Free",
    url: "https://www.deeplearning.ai/short-courses/",
    category: "AI 2026",
    tags: ["LLM", "RAG", "Agents"],
    featured: true,
  },
  {
    id: "langgraph",
    name: "LangGraph Documentation",
    provider: "LangChain",
    level: "Intermediate",
    duration: "Tự học",
    cost: "Free",
    url: "https://langchain-ai.github.io/langgraph/",
    category: "AI 2026",
    tags: ["Agents", "LangGraph"],
  },
  {
    id: "mcp",
    name: "Model Context Protocol (MCP)",
    provider: "Anthropic",
    level: "Intermediate",
    duration: "Tự học",
    cost: "Free",
    url: "https://modelcontextprotocol.io/",
    category: "AI 2026",
    tags: ["MCP", "Tools"],
  },
  {
    id: "hf-llm",
    name: "Hugging Face LLM Course",
    provider: "Hugging Face",
    level: "Intermediate",
    duration: "Tự học",
    cost: "Free",
    url: "https://huggingface.co/learn/llm-course",
    category: "AI 2026",
    tags: ["LLM", "NLP"],
  },

  // ── BI tools ──
  {
    id: "powerbi",
    name: "Power BI Training",
    provider: "Microsoft Learn",
    level: "Beginner",
    duration: "Tự học",
    cost: "Free",
    url: "https://learn.microsoft.com/en-us/training/powerplatform/power-bi",
    category: "BI",
    tags: ["Power BI", "Dashboard"],
  },
  {
    id: "tableau",
    name: "Tableau Free Training",
    provider: "Tableau",
    level: "Beginner",
    duration: "Tự học",
    cost: "Free",
    url: "https://www.tableau.com/learn/training",
    category: "BI",
    tags: ["Tableau", "Dashboard"],
  },
  {
    id: "dbt",
    name: "dbt Fundamentals",
    provider: "dbt Labs",
    level: "Intermediate",
    duration: "Tự học",
    cost: "Free",
    url: "https://learn.getdbt.com/",
    category: "BI",
    tags: ["dbt", "Analytics Engineering"],
  },
];

export const COURSE_BY_ID = Object.fromEntries(
  COURSES.map((c) => [c.id, c]),
) as Record<string, Course>;

export const COURSE_CATEGORIES = [
  "Python",
  "Math",
  "SQL",
  "Data",
  "ML",
  "DL",
  "Responsible AI",
  "MLOps",
  "AI 2026",
  "BI",
] as const;
