import type { Phase } from "./types";

/** 10 learning phases — Beginner → AI Engineer. Ordered, stacked dependencies. */
export const PHASES: Phase[] = [
  {
    id: "p1",
    number: 1,
    track: "Core Computing",
    color: "emerald",
    title: "Setup & Python Cơ Bản",
    tagline: "Viết được code Python có kiểm thử + repo GitHub đầu tiên",
    objective:
      "Cài đặt được môi trường lập trình và viết được những đoạn code Python nhỏ, có kiểm thử.",
    why: "Python là ngôn ngữ thống trị ngành Data Science. Mọi thứ về sau — pandas, scikit-learn, PyTorch — đều viết bằng Python. Git giúp bạn lưu trữ và 'khoe' code trên GitHub (nhà tuyển dụng sẽ xem).",
    learn: [
      "Cài Python, VS Code (hoặc Google Colab), tạo tài khoản GitHub",
      "Biến, chuỗi, danh sách, vòng lặp, điều kiện if/else",
      "Hàm, module, đọc/ghi file, xử lý lỗi (exceptions)",
      "Tư duy hướng đối tượng cơ bản (OOP)",
      "Git: commit, push, pull, branch",
    ],
    skills: ["Python", "OOP cơ bản", "Git workflow", "Unit testing"],
    tools: ["Python", "VS Code", "Jupyter", "Google Colab", "Git", "GitHub"],
    duration: "4 tuần",
    weeks: 4,
    difficulty: "Beginner",
    outcome:
      "Bạn viết và test được các script nhỏ; đã có repo đầu tiên trên GitHub.",
    deliverables: ["Repo GitHub đầu tiên", "Mini CSV parser", "Unit tests cơ bản"],
    checklist: [
      "Cài được Python + VS Code (hoặc dùng được Colab)",
      "Tạo tài khoản GitHub và push được repo đầu tiên",
      "Viết được hàm Python với tham số và return",
      "Đọc/ghi được file CSV bằng Python thuần",
      "Xử lý được lỗi với try/except",
      "Viết được unit test đơn giản (assert)",
      "Hiểu được commit, push, pull, branch của Git",
    ],
    courseIds: ["cs50p", "py-tutorial", "kaggle-python", "pro-git", "think-python"],
  },
  {
    id: "p2",
    number: 2,
    track: "Math & Statistics",
    color: "blue",
    title: "Toán & Thống Kê Nền Tảng",
    tagline: "Hiểu trực giác phân phối, kiểm định giả thuyết, đại số tuyến tính",
    objective:
      "Hiểu và giải thích được các khái niệm: phân phối, trung bình/phương sai, khoảng tin cậy, kiểm định giả thuyết.",
    why: "Đây là phần người mới hay bỏ qua nhưng lại quan trọng nhất để phân biệt người làm data giỏi và người chỉ biết gọi thư viện. Bạn cần thống kê để biết một kết quả là thật hay chỉ may rủi. Bạn KHÔNG cần học như sinh viên chuyên Toán — chỉ cần đủ để hiểu trực giác và áp dụng.",
    learn: [
      "Hàm số, đồ thị, phương trình tuyến tính, độ dốc (slope)",
      "Xác suất: sự kiện, xác suất có điều kiện, phân phối, kỳ vọng",
      "Thống kê mô tả: trung bình/trung vị/phương sai, outliers, histogram",
      "Thống kê suy luận: khoảng tin cậy, kiểm định giả thuyết, p-value",
      "Đại số tuyến tính: trực giác về vector và ma trận",
    ],
    skills: ["Xác suất", "Thống kê suy luận", "Đại số tuyến tính", "Mô phỏng"],
    tools: ["Khan Academy", "Jupyter", "NumPy", "Giấy bút ✏️"],
    duration: "4 tuần",
    weeks: 4,
    difficulty: "Beginner",
    outcome:
      "Bạn giải thích được khoảng tin cậy và một kiểm định giả thuyết bằng ngôn ngữ thường ngày.",
    deliverables: ["Notebook mô phỏng (NumPy)", "Writeup kiểm định giả thuyết"],
    checklist: [
      "Giải thích được histogram và phân phối nói lên điều gì",
      "Tính được trung bình, trung vị, phương sai và biết khi nào dùng cái nào",
      "Hiểu p-value là gì (và KHÔNG hiểu sai nó)",
      "Giải thích được khoảng tin cậy bằng tiếng Việt đơn giản",
      "Viết được một notebook mô phỏng (simulation) bằng NumPy",
      "Hiểu trực giác vector và ma trận là gì",
    ],
    courseIds: ["khan-stats", "openintro", "mit-1805", "mit-1806", "think-stats"],
  },
  {
    id: "p3",
    number: 3,
    track: "Data Work",
    color: "amber",
    title: "SQL (Học song song)",
    tagline: "Truy vấn database từ cơ bản đến window functions & CTE",
    objective:
      "Truy vấn được dữ liệu từ database quan hệ, từ cơ bản đến window functions.",
    why: "SQL là kỹ năng được dùng nhiều nhất trong mọi công việc data thực tế. Dữ liệu công ty nằm trong database, và SQL là cách bạn lấy nó ra. Đặc biệt với Data Analyst, SQL gần như là kỹ năng số 1.",
    learn: [
      "SELECT, WHERE, ORDER BY, hàm tổng hợp (COUNT, SUM, AVG)",
      "JOIN (inner, left, right), GROUP BY / HAVING, subqueries",
      "Window functions, CTEs (Common Table Expressions)",
      "Debug truy vấn, tối ưu cơ bản",
    ],
    skills: ["SQL", "JOIN", "Window functions", "CTE", "Business metrics"],
    tools: ["PostgreSQL", "DBeaver", "SQLite", "DuckDB"],
    duration: "3 tuần",
    weeks: 3,
    difficulty: "Beginner",
    outcome:
      "Bạn tái tạo được một bộ chỉ số kinh doanh (business metrics) bằng SQL.",
    deliverables: ["25+ bài SQL", "Tái tạo bộ business metric (MAU, retention)"],
    checklist: [
      "Viết được câu SELECT với WHERE và ORDER BY",
      "Dùng được các JOIN (đặc biệt LEFT JOIN)",
      "Dùng GROUP BY + HAVING để tổng hợp",
      "Viết được window function (ROW_NUMBER, RANK)",
      "Dùng CTE để chia nhỏ truy vấn phức tạp",
      "Tái tạo được 1 chỉ số kinh doanh (ví dụ: MAU, retention)",
    ],
    courseIds: ["pg-tutorial", "khan-sql", "ucdavis-sql", "duckdb"],
  },
  {
    id: "p4",
    number: 4,
    track: "Data Work",
    color: "amber",
    title: "pandas, Làm Sạch Dữ Liệu & EDA",
    tagline: "Đọc, làm sạch, biến đổi & phân tích dữ liệu dạng bảng",
    objective:
      "Đọc, làm sạch, biến đổi và phân tích dữ liệu dạng bảng bằng pandas.",
    why: "Trong thực tế, 80% thời gian làm data là làm sạch dữ liệu. Dữ liệu thật luôn bẩn: thiếu giá trị, sai kiểu, trùng lặp. pandas là công cụ số 1 để xử lý việc này trong Python.",
    learn: [
      "Series & DataFrame, indexing, filtering, đọc CSV/Parquet/JSON",
      "Xử lý missing data, sai kiểu, giá trị phân loại, ngày tháng, trùng lặp",
      "merge, groupby, pivot, melt, split-apply-combine",
      "EDA: tóm tắt, tìm quy luật, phát hiện bất thường",
    ],
    skills: ["pandas", "Data cleaning", "EDA", "Reshaping"],
    tools: ["pandas", "NumPy", "Jupyter", "Polars"],
    duration: "3 tuần",
    weeks: 3,
    difficulty: "Beginner",
    outcome: "Bạn làm được notebook 'dọn dữ liệu bẩn' và một báo cáo EDA ngắn.",
    deliverables: ["'Messy data cleanup' notebook", "Báo cáo EDA hoàn chỉnh"],
    checklist: [
      "Đọc được CSV, JSON, Parquet vào DataFrame",
      "Xử lý được missing values và trùng lặp",
      "Dùng được groupby + aggregate",
      "Dùng được merge để nối bảng (như JOIN trong SQL)",
      "Pivot/melt để reshape dữ liệu",
      "Hoàn thành 1 notebook EDA hoàn chỉnh trên dataset thật",
    ],
    courseIds: ["pandas-start", "kaggle-pandas", "numpy"],
  },
  {
    id: "p5",
    number: 5,
    track: "Data Work",
    color: "amber",
    title: "Visualization & Storytelling",
    tagline: "Vẽ biểu đồ rõ ràng & kể chuyện bằng dữ liệu",
    objective:
      "Vẽ biểu đồ rõ ràng và kể được câu chuyện từ dữ liệu cho người không chuyên.",
    why: "Phân tích giỏi mà không truyền đạt được thì vô nghĩa. Communication là 1 trong những kỹ năng được nhà tuyển dụng đánh giá cao nhất. Một biểu đồ tốt thuyết phục sếp hơn 100 dòng số.",
    learn: [
      "Các loại biểu đồ: line, bar, histogram, scatter, box plot — khi nào dùng cái nào",
      "Annotation, thể hiện độ bất định, biểu đồ phù hợp với khán giả",
      "Tư duy dashboard, báo cáo trực quan 1 trang",
    ],
    skills: ["Visualization", "Storytelling", "Dashboard", "Communication"],
    tools: ["Matplotlib", "Seaborn", "Plotly", "Power BI", "Tableau"],
    duration: "2 tuần",
    weeks: 2,
    difficulty: "Beginner",
    outcome:
      "Một 'deck' gồm 6 biểu đồ EDA + một báo cáo trực quan 1 trang.",
    deliverables: ["Deck 6 biểu đồ", "Báo cáo 1 trang hướng quyết định"],
    checklist: [
      "Biết chọn đúng loại biểu đồ cho từng tình huống",
      "Vẽ được biểu đồ có tiêu đề, nhãn trục, chú thích rõ ràng",
      "Tạo được deck 6 biểu đồ kể 1 câu chuyện liền mạch",
      "Viết được báo cáo 1 trang hướng tới quyết định",
      "(Analyst) Làm được 1 dashboard cơ bản trên Power BI/Tableau",
    ],
    courseIds: ["matplotlib", "seaborn", "kaggle-viz", "powerbi", "tableau"],
  },
  {
    id: "p6",
    number: 6,
    track: "Machine Learning",
    color: "purple",
    title: "Machine Learning Cơ Bản",
    tagline: "Xây & đánh giá mô hình ML cổ điển một cách trung thực",
    objective:
      "Xây và đánh giá được mô hình ML cổ điển một cách trung thực; biết bảo vệ lựa chọn metric.",
    why: "Đây là trái tim của Data Science. Nhưng quan trọng hơn việc 'chạy được mô hình' là đánh giá đúng: tránh data leakage, chọn metric phù hợp, hiểu overfitting. Google MLCC nhấn mạnh điều này hơn cả thuật toán.",
    learn: [
      "Regression, Classification, baseline, train/test split",
      "Logistic regression, threshold, class imbalance",
      "Decision trees, random forests, gradient boosting (trực giác)",
      "Cross-validation, data leakage, bias-variance, chọn metric",
      "Feature engineering, scaling, encoding, scikit-learn pipelines",
    ],
    skills: [
      "Regression",
      "Classification",
      "Model evaluation",
      "Feature engineering",
      "Pipelines",
    ],
    tools: ["scikit-learn", "pandas", "Jupyter", "XGBoost", "LightGBM"],
    duration: "5 tuần",
    weeks: 5,
    difficulty: "Intermediate",
    outcome:
      "Bạn bảo vệ được lựa chọn metric, phát hiện được leakage, và so sánh trung thực ≥3 mô hình.",
    deliverables: [
      "Bảng so sánh ≥3 mô hình",
      "Memo bảo vệ metric",
      "scikit-learn pipeline tái sử dụng",
    ],
    checklist: [
      "Xây được mô hình regression và phân tích residual",
      "Xây được mô hình classification + đọc confusion matrix",
      "So sánh được ≥3 mô hình trong một bảng",
      "Dùng cross-validation đúng cách",
      "Phát hiện và tránh được data leakage",
      "Giải thích được 'tại sao accuracy đôi khi là metric tệ'",
      "Đóng gói được một scikit-learn pipeline tái sử dụng",
    ],
    courseIds: ["google-mlcc", "ng-ml", "sklearn-start", "sklearn-model", "kaggle-ml", "islp"],
  },
  {
    id: "p7",
    number: 7,
    track: "Machine Learning",
    color: "purple",
    title: "Unsupervised, Time Series & Responsible AI",
    tagline: "Clustering, dự báo, A/B testing & đạo đức AI",
    objective:
      "Áp dụng học không giám sát, dự báo chuỗi thời gian cơ bản, và hiểu Responsible AI.",
    why: "Không phải bài toán nào cũng có 'nhãn'. Clustering giúp phân khúc khách hàng. Time series cho dự báo doanh thu. Năm 2026, Responsible AI (công bằng, minh bạch, rủi ro) đã thành kỹ năng nền tảng, không còn là tùy chọn.",
    learn: [
      "Clustering, PCA, tư duy phân khúc (segmentation)",
      "Time series: xu hướng/mùa vụ, lag features, rolling windows",
      "A/B testing cơ bản, power, cẩn trọng với nhân quả",
      "Responsible AI: fairness, governance, documentation, model card",
    ],
    skills: ["Clustering", "PCA", "Time series", "A/B testing", "Responsible AI"],
    tools: ["scikit-learn", "statsmodels", "NIST AI RMF", "OECD AI Principles"],
    duration: "3 tuần",
    weeks: 3,
    difficulty: "Intermediate",
    outcome:
      "Một notebook phân khúc khách hàng + một bản brief thiết kế thí nghiệm + một model card.",
    deliverables: [
      "Notebook phân khúc khách hàng",
      "Brief thiết kế A/B test",
      "Model card / risk note",
    ],
    checklist: [
      "Chạy được clustering và diễn giải các cụm",
      "Dùng PCA để giảm chiều dữ liệu",
      "Làm được 1 dự báo time series có benchmark",
      "Thiết kế được 1 thí nghiệm A/B đơn giản",
      "Viết được 1 model card / ghi chú rủi ro cho mô hình",
    ],
    courseIds: ["google-mlcc", "nist-rmf", "kaggle-timeseries", "kaggle-ethics", "oecd-ai"],
  },
  {
    id: "p8",
    number: 8,
    track: "Delivery",
    color: "rose",
    title: "Deep Learning Cơ Bản",
    tagline: "Hiểu trực giác neural network & huấn luyện mô hình DL",
    objective:
      "Hiểu trực giác mạng neural và huấn luyện được một mô hình deep learning đơn giản.",
    why: "Deep learning là nền tảng của AI hiện đại (computer vision, NLP, LLM). Bạn cần hiểu nó để bước vào thế giới AI 2026. Nhưng nhớ: chỉ học sau khi đã vững ML cổ điển.",
    learn: [
      "Perceptron, hàm kích hoạt, trực giác backpropagation",
      "Tensors, data loaders, vòng lặp huấn luyện, đánh giá",
      "Embeddings, trực giác retrieval, workflow phân tích dùng prompt",
    ],
    skills: ["Neural networks", "PyTorch", "Training loop", "Embeddings"],
    tools: ["PyTorch", "TensorFlow/Keras", "Google Colab", "Hugging Face"],
    duration: "3 tuần",
    weeks: 3,
    difficulty: "Intermediate",
    outcome:
      "Huấn luyện được 1 mạng neural đơn giản + 1 bài tập embedding/prompt.",
    deliverables: ["Train 1 NN đơn giản", "Bài tập embedding/prompt"],
    checklist: [
      "Giải thích được backprop bằng lời (không cần đạo hàm chi tiết)",
      "Viết được vòng lặp huấn luyện cơ bản trong PyTorch",
      "Huấn luyện 1 mô hình NN đơn giản và đánh giá nó",
      "Hiểu embeddings là gì và dùng để làm gì",
    ],
    courseIds: ["pytorch-basics", "tensorflow", "fastai", "ng-dl", "hf-learn"],
  },
  {
    id: "p9",
    number: 9,
    track: "Delivery",
    color: "rose",
    title: "MLOps & Deployment",
    tagline: "Biến mô hình từ notebook thành sản phẩm deploy được",
    objective:
      "Biến mô hình từ notebook thành sản phẩm người khác chạy được; expose một API/app.",
    why: "Đây là 'last mile' mà hầu hết người mới bỏ qua — và cũng là điều khiến CV của bạn nổi bật năm 2026. Nhà tuyển dụng muốn thấy bạn deploy được, không chỉ phân tích.",
    learn: [
      "Experiment tracking: log params, metrics, so sánh mô hình (MLflow)",
      "Versioning dữ liệu/mô hình (DVC), môi trường tái lập được",
      "FastAPI: phục vụ mô hình qua endpoint",
      "Docker: đóng gói app để chạy ở mọi nơi",
      "Streamlit/Gradio: tạo demo app từ mô hình",
    ],
    skills: ["MLflow", "DVC", "FastAPI", "Docker", "Streamlit", "Reproducibility"],
    tools: ["MLflow", "DVC", "FastAPI", "Docker", "Streamlit", "Gradio"],
    duration: "4 tuần",
    weeks: 4,
    difficulty: "Advanced",
    outcome:
      "Một API inference chạy được + một demo app đã đóng gói Docker.",
    deliverables: ["FastAPI inference endpoint", "Docker image", "Reproducible repo"],
    checklist: [
      "Theo dõi experiment bằng MLflow (params, metrics)",
      "Version hóa dữ liệu/mô hình với DVC",
      "Phục vụ mô hình qua FastAPI endpoint",
      "Đóng gói app bằng Docker",
      "Tạo demo app bằng Streamlit/Gradio",
      "Chạy lại được toàn bộ project từ môi trường sạch",
    ],
    courseIds: ["mlflow", "dvc", "fastapi", "docker", "streamlit", "fsdl"],
  },
  {
    id: "p10",
    number: 10,
    track: "Modern AI 2026",
    color: "pink",
    title: "Cloud + AI/LLM Engineering 2026",
    tagline: "RAG, Vector DB, AI Agents, LangGraph & MCP",
    advanced: true,
    objective:
      "Hiểu nền tảng cloud và xây được ứng dụng AI hiện đại (RAG, agent) trên nền mô hình có sẵn.",
    why: "⚠️ Phần này đặt ở CUỐI lộ trình có chủ đích. Người mới TUYỆT ĐỐI KHÔNG học LLM/Agent ngay từ đầu — bạn chỉ chạm vào đây sau khi vững Phase 1-9. Nếu không, bạn sẽ chỉ biết 'gọi API' mà không hiểu gì bên dưới.",
    learn: [
      "Cloud: chọn 1 nhà cung cấp (AWS/GCP/Azure), storage, compute, managed ML",
      "LLM: cách hoạt động, prompting, context window, hạn chế",
      "RAG: kết hợp LLM với dữ liệu riêng",
      "Vector Database: embeddings, similarity search",
      "AI Agents & Agentic AI: mô hình tự lập kế hoạch và hành động",
      "LangGraph: xây luồng agent có trạng thái; MCP: kết nối AI với công cụ",
    ],
    skills: ["LLM", "RAG", "Vector DB", "AI Agents", "LangGraph", "MCP"],
    tools: [
      "AWS/GCP/Azure",
      "OpenAI/Anthropic API",
      "LangChain",
      "LangGraph",
      "Chroma/pgvector",
      "MCP",
    ],
    duration: "4 tuần+",
    weeks: 4,
    difficulty: "Advanced",
    outcome:
      "Một mini-lab trên cloud + một ứng dụng RAG hoàn chỉnh (Portfolio Project 6).",
    deliverables: ["Cloud mini-lab", "Ứng dụng RAG hoàn chỉnh"],
    checklist: [
      "Hiểu nền tảng 1 nhà cung cấp cloud (storage, compute)",
      "Gọi được LLM API và viết prompt hiệu quả",
      "Hiểu embeddings + vector database hoạt động thế nào",
      "Xây được 1 ứng dụng RAG đơn giản (hỏi đáp trên tài liệu riêng)",
      "Hiểu khái niệm AI Agent và khi nào nên/không nên dùng",
      "Thử nghiệm LangGraph hoặc MCP ở mức cơ bản",
    ],
    courseIds: ["google-mle", "aws-ml", "dlai-short", "langgraph", "mcp", "hf-llm"],
  },
];

export const PHASE_BY_ID = Object.fromEntries(
  PHASES.map((p) => [p.id, p]),
) as Record<string, Phase>;
