import type { Phase } from "./types";

/** 10 learning phases — Beginner → AI Engineer. Ordered, stacked dependencies. */
export const PHASES: Phase[] = [
  {
    id: "p1",
    number: 1,
    track: "Core Computing",
    color: "emerald",
    title: "Setup & Python Basics",
    tagline: "Write tested Python + ship your first GitHub repo",
    objective:
      "Set up a working programming environment and write small, tested Python scripts.",
    why: "Python is the dominant language in Data Science. Everything later — pandas, scikit-learn, PyTorch — is built on it. Git lets you store and showcase your code on GitHub (recruiters will look).",
    learn: [
      "Install Python, VS Code (or Google Colab), create a GitHub account",
      "Variables, strings, lists, loops, conditionals (if/else)",
      "Functions, modules, file I/O, exception handling",
      "Basic object-oriented programming (OOP)",
      "Git: commit, push, pull, branch",
    ],
    skills: ["Python", "Basic OOP", "Git workflow", "Unit testing"],
    tools: ["Python", "VS Code", "Jupyter", "Google Colab", "Git", "GitHub"],
    duration: "4 weeks",
    weeks: 4,
    difficulty: "Beginner",
    outcome:
      "You can write and test small scripts, and you have your first repo on GitHub.",
    deliverables: ["First GitHub repo", "Mini CSV parser", "Basic unit tests"],
    checklist: [
      "Install Python + VS Code (or be comfortable with Colab)",
      "Create a GitHub account and push your first repo",
      "Write a Python function with parameters and a return value",
      "Read/write a CSV file with pure Python",
      "Handle errors with try/except",
      "Write a simple unit test (assert)",
      "Understand Git commit, push, pull, branch",
    ],
    courseIds: ["cs50p", "py-tutorial", "kaggle-python", "pro-git", "think-python"],
  },
  {
    id: "p2",
    number: 2,
    track: "Math & Statistics",
    color: "blue",
    title: "Math & Statistics Foundations",
    tagline: "Intuition for distributions, hypothesis testing, linear algebra",
    objective:
      "Understand and explain core concepts: distributions, mean/variance, confidence intervals, and hypothesis testing.",
    why: "Beginners often skip this, but it's the most important thing that separates strong data people from those who only call libraries. You need statistics to tell whether a result is real or just luck. You do NOT need to study like a math major — just enough to build intuition and apply it.",
    learn: [
      "Functions, graphs, linear equations, slope",
      "Probability: events, conditional probability, distributions, expectation",
      "Descriptive statistics: mean/median/variance, outliers, histograms",
      "Inferential statistics: confidence intervals, hypothesis tests, p-value",
      "Linear algebra: intuition for vectors and matrices",
    ],
    skills: ["Probability", "Inferential stats", "Linear algebra", "Simulation"],
    tools: ["Khan Academy", "Jupyter", "NumPy", "Pen & paper ✏️"],
    duration: "4 weeks",
    weeks: 4,
    difficulty: "Beginner",
    outcome:
      "You can explain a confidence interval and a hypothesis test in plain language.",
    deliverables: ["Simulation notebook (NumPy)", "Hypothesis-test writeup"],
    checklist: [
      "Explain what a histogram and a distribution tell you",
      "Compute mean, median, variance and know when to use each",
      "Understand what a p-value is (and what it is NOT)",
      "Explain a confidence interval in simple terms",
      "Write a simulation notebook in NumPy",
      "Build intuition for what vectors and matrices are",
    ],
    courseIds: ["khan-stats", "openintro", "mit-1805", "mit-1806", "think-stats"],
  },
  {
    id: "p3",
    number: 3,
    track: "Data Work",
    color: "amber",
    title: "SQL (Learn in Parallel)",
    tagline: "Query databases from basics to window functions & CTEs",
    objective:
      "Query data from relational databases, from basics to window functions.",
    why: "SQL is the most-used skill in every real data job. Company data lives in databases, and SQL is how you get it out. For Data Analysts especially, SQL is practically skill #1.",
    learn: [
      "SELECT, WHERE, ORDER BY, aggregate functions (COUNT, SUM, AVG)",
      "JOIN (inner, left, right), GROUP BY / HAVING, subqueries",
      "Window functions, CTEs (Common Table Expressions)",
      "Debugging queries, basic optimization",
    ],
    skills: ["SQL", "JOIN", "Window functions", "CTE", "Business metrics"],
    tools: ["PostgreSQL", "DBeaver", "SQLite", "DuckDB"],
    duration: "3 weeks",
    weeks: 3,
    difficulty: "Beginner",
    outcome: "You can reproduce a set of business metrics in SQL.",
    deliverables: ["25+ SQL exercises", "Reproduce a business metric (MAU, retention)"],
    checklist: [
      "Write a SELECT with WHERE and ORDER BY",
      "Use JOINs (especially LEFT JOIN)",
      "Use GROUP BY + HAVING to aggregate",
      "Write a window function (ROW_NUMBER, RANK)",
      "Use a CTE to break down a complex query",
      "Reproduce one business metric (e.g. MAU, retention)",
    ],
    courseIds: ["pg-tutorial", "khan-sql", "ucdavis-sql", "duckdb"],
  },
  {
    id: "p4",
    number: 4,
    track: "Data Work",
    color: "amber",
    title: "pandas, Data Cleaning & EDA",
    tagline: "Read, clean, transform & analyze tabular data",
    objective:
      "Read, clean, transform, and analyze tabular data with pandas.",
    why: "In practice, 80% of data work is cleaning. Real data is always messy: missing values, wrong types, duplicates. pandas is the #1 tool for handling this in Python.",
    learn: [
      "Series & DataFrame, indexing, filtering, reading CSV/Parquet/JSON",
      "Handling missing data, wrong types, categoricals, dates, duplicates",
      "merge, groupby, pivot, melt, split-apply-combine",
      "EDA: summarizing, finding patterns, spotting anomalies",
    ],
    skills: ["pandas", "Data cleaning", "EDA", "Reshaping"],
    tools: ["pandas", "NumPy", "Jupyter", "Polars"],
    duration: "3 weeks",
    weeks: 3,
    difficulty: "Beginner",
    outcome: "You can produce a 'messy data cleanup' notebook and a short EDA report.",
    deliverables: ["'Messy data cleanup' notebook", "Complete EDA report"],
    checklist: [
      "Read CSV, JSON, Parquet into a DataFrame",
      "Handle missing values and duplicates",
      "Use groupby + aggregate",
      "Use merge to join tables (like a SQL JOIN)",
      "Pivot/melt to reshape data",
      "Complete one full EDA notebook on a real dataset",
    ],
    courseIds: ["pandas-start", "kaggle-pandas", "numpy"],
  },
  {
    id: "p5",
    number: 5,
    track: "Data Work",
    color: "amber",
    title: "Visualization & Storytelling",
    tagline: "Draw clear charts & tell stories with data",
    objective:
      "Create clear charts and tell a data story to non-technical audiences.",
    why: "Great analysis that can't be communicated is worthless. Communication is one of the most valued skills by recruiters. A good chart convinces a manager more than 100 rows of numbers.",
    learn: [
      "Chart types: line, bar, histogram, scatter, box plot — and when to use each",
      "Annotation, showing uncertainty, charts matched to the audience",
      "Dashboard thinking, one-page visual reports",
    ],
    skills: ["Visualization", "Storytelling", "Dashboards", "Communication"],
    tools: ["Matplotlib", "Seaborn", "Plotly", "Power BI", "Tableau"],
    duration: "2 weeks",
    weeks: 2,
    difficulty: "Beginner",
    outcome:
      "A deck of 6 EDA charts plus a one-page visual report.",
    deliverables: ["6-chart deck", "One-page decision-oriented report"],
    checklist: [
      "Pick the right chart type for each situation",
      "Draw charts with clear titles, axis labels, and annotations",
      "Build a 6-chart deck that tells one coherent story",
      "Write a one-page report aimed at a decision",
      "(Analyst) Build a basic dashboard in Power BI/Tableau",
    ],
    courseIds: ["matplotlib", "seaborn", "kaggle-viz", "powerbi", "tableau"],
  },
  {
    id: "p6",
    number: 6,
    track: "Machine Learning",
    color: "purple",
    title: "Machine Learning Basics",
    tagline: "Build & honestly evaluate classic ML models",
    objective:
      "Build and honestly evaluate classic ML models; defend your choice of metric.",
    why: "This is the heart of Data Science. But more important than 'getting a model to run' is evaluating it correctly: avoiding data leakage, choosing the right metric, understanding overfitting. Google's MLCC stresses this even more than algorithms.",
    learn: [
      "Regression, Classification, baselines, train/test split",
      "Logistic regression, thresholds, class imbalance",
      "Decision trees, random forests, gradient boosting (intuition)",
      "Cross-validation, data leakage, bias-variance, metric choice",
      "Feature engineering, scaling, encoding, scikit-learn pipelines",
    ],
    skills: [
      "Regression",
      "Classification",
      "Model evaluation",
      "Feature engineering",
      "Pipelines",
    ],
    tools: ["scikit-learn", "pandas", "Jupyter", "XGBoost", "LightGBM"],
    duration: "5 weeks",
    weeks: 5,
    difficulty: "Intermediate",
    outcome:
      "You can defend your metric choice, detect leakage, and honestly compare 3+ models.",
    deliverables: [
      "3+ model comparison table",
      "Metric-defense memo",
      "Reusable scikit-learn pipeline",
    ],
    checklist: [
      "Build a regression model and analyze residuals",
      "Build a classification model and read a confusion matrix",
      "Compare 3+ models in one table",
      "Use cross-validation correctly",
      "Detect and avoid data leakage",
      "Explain 'why accuracy is sometimes a bad metric'",
      "Package a reusable scikit-learn pipeline",
    ],
    courseIds: ["google-mlcc", "ng-ml", "sklearn-start", "sklearn-model", "kaggle-ml", "islp"],
  },
  {
    id: "p7",
    number: 7,
    track: "Machine Learning",
    color: "purple",
    title: "Unsupervised, Time Series & Responsible AI",
    tagline: "Clustering, forecasting, A/B testing & AI ethics",
    objective:
      "Apply unsupervised learning, basic time-series forecasting, and understand Responsible AI.",
    why: "Not every problem has labels. Clustering helps segment customers. Time series powers revenue forecasts. And in 2026, Responsible AI (fairness, transparency, risk) has become a foundational skill — no longer optional.",
    learn: [
      "Clustering, PCA, segmentation thinking",
      "Time series: trend/seasonality, lag features, rolling windows",
      "Basic A/B testing, power, caution around causality",
      "Responsible AI: fairness, governance, documentation, model cards",
    ],
    skills: ["Clustering", "PCA", "Time series", "A/B testing", "Responsible AI"],
    tools: ["scikit-learn", "statsmodels", "NIST AI RMF", "OECD AI Principles"],
    duration: "3 weeks",
    weeks: 3,
    difficulty: "Intermediate",
    outcome:
      "A customer-segmentation notebook, an experiment-design brief, and a model card.",
    deliverables: [
      "Customer-segmentation notebook",
      "A/B test design brief",
      "Model card / risk note",
    ],
    checklist: [
      "Run clustering and interpret the clusters",
      "Use PCA for dimensionality reduction",
      "Make a time-series forecast with a benchmark",
      "Design a simple A/B test",
      "Write a model card / risk note for a model",
    ],
    courseIds: ["google-mlcc", "nist-rmf", "kaggle-timeseries", "kaggle-ethics", "oecd-ai"],
  },
  {
    id: "p8",
    number: 8,
    track: "Delivery",
    color: "rose",
    title: "Deep Learning Basics",
    tagline: "Neural network intuition & training a DL model",
    objective:
      "Build intuition for neural networks and train a simple deep learning model.",
    why: "Deep learning underpins modern AI (computer vision, NLP, LLMs). You need it to step into the 2026 AI world. But remember: only after you're solid on classic ML.",
    learn: [
      "Perceptron, activation functions, backpropagation intuition",
      "Tensors, data loaders, training loop, evaluation",
      "Embeddings, retrieval intuition, prompt-based analysis workflow",
    ],
    skills: ["Neural networks", "PyTorch", "Training loop", "Embeddings"],
    tools: ["PyTorch", "TensorFlow/Keras", "Google Colab", "Hugging Face"],
    duration: "3 weeks",
    weeks: 3,
    difficulty: "Intermediate",
    outcome:
      "You can train a simple neural network plus one embedding/prompt exercise.",
    deliverables: ["Train a simple NN", "Embedding/prompt exercise"],
    checklist: [
      "Explain backprop in words (no detailed derivatives needed)",
      "Write a basic training loop in PyTorch",
      "Train a simple NN model and evaluate it",
      "Understand what embeddings are and what they're for",
    ],
    courseIds: ["pytorch-basics", "tensorflow", "fastai", "ng-dl", "hf-learn"],
  },
  {
    id: "p9",
    number: 9,
    track: "Delivery",
    color: "rose",
    title: "MLOps & Deployment",
    tagline: "Turn a notebook model into a deployable product",
    objective:
      "Turn a model from a notebook into something others can run; expose an API/app.",
    why: "This is the 'last mile' most beginners skip — and it's what makes your CV stand out in 2026. Recruiters want to see you can deploy, not just analyze.",
    learn: [
      "Experiment tracking: log params, metrics, compare models (MLflow)",
      "Data/model versioning (DVC), reproducible environments",
      "FastAPI: serve a model via an endpoint",
      "Docker: package an app to run anywhere",
      "Streamlit/Gradio: build a demo app from a model",
    ],
    skills: ["MLflow", "DVC", "FastAPI", "Docker", "Streamlit", "Reproducibility"],
    tools: ["MLflow", "DVC", "FastAPI", "Docker", "Streamlit", "Gradio"],
    duration: "4 weeks",
    weeks: 4,
    difficulty: "Advanced",
    outcome:
      "A working inference API plus a demo app packaged with Docker.",
    deliverables: ["FastAPI inference endpoint", "Docker image", "Reproducible repo"],
    checklist: [
      "Track experiments with MLflow (params, metrics)",
      "Version data/models with DVC",
      "Serve a model via a FastAPI endpoint",
      "Package an app with Docker",
      "Build a demo app with Streamlit/Gradio",
      "Re-run the whole project from a clean environment",
    ],
    courseIds: ["mlflow", "dvc", "fastapi", "docker", "streamlit", "fsdl"],
  },
  {
    id: "p10",
    number: 10,
    track: "Modern AI 2026",
    color: "pink",
    title: "Cloud + AI/LLM Engineering 2026",
    tagline: "RAG, Vector DBs, AI Agents, LangGraph & MCP",
    advanced: true,
    objective:
      "Understand cloud fundamentals and build modern AI apps (RAG, agents) on top of existing models.",
    why: "⚠️ This phase is intentionally last. Beginners should NEVER start with LLMs/agents — you only get here after you're solid on Phases 1-9. Otherwise you'll just 'call an API' without understanding anything underneath.",
    learn: [
      "Cloud: pick one provider (AWS/GCP/Azure), storage, compute, managed ML",
      "LLMs: how they work, prompting, context windows, limitations",
      "RAG: combine an LLM with your own data",
      "Vector databases: embeddings, similarity search",
      "AI Agents & Agentic AI: models that plan and act",
      "LangGraph: build stateful agent flows; MCP: connect AI to tools",
    ],
    skills: ["LLM", "RAG", "Vector DB", "AI Agents", "LangGraph", "MCP"],
    tools: [
      "AWS/GCP/Azure",
      "OpenAI/Anthropic API",
      "LangChain",
      "LangGraph",
      "Chroma/pgvector",
      "MCP",
    ],
    duration: "4+ weeks",
    weeks: 4,
    difficulty: "Advanced",
    outcome:
      "A cloud mini-lab plus a complete RAG application (Portfolio Project 6).",
    deliverables: ["Cloud mini-lab", "Complete RAG application"],
    checklist: [
      "Understand one cloud provider's basics (storage, compute)",
      "Call an LLM API and write effective prompts",
      "Understand how embeddings + vector databases work",
      "Build a simple RAG app (Q&A over your own documents)",
      "Understand AI agents and when to use / not use them",
      "Experiment with LangGraph or MCP at a basic level",
    ],
    courseIds: ["google-mle", "aws-ml", "dlai-short", "langgraph", "mcp", "hf-llm"],
  },
];

export const PHASE_BY_ID = Object.fromEntries(
  PHASES.map((p) => [p.id, p]),
) as Record<string, Phase>;
