import type { Plan } from "./types";

export const PLANS: Plan[] = [
  {
    id: "6",
    months: 6,
    title: "Tăng Tốc",
    audience: "Người chuyển ngành có thời gian học được bảo vệ",
    hoursPerWeek: "15-18 giờ/tuần",
    totalHours: "~360-430 giờ",
    rows: [
      { label: "Tuần 1-2", focus: "Setup, Python cơ bản, Git", course: "CS50P, Python Tutorial", milestone: "Repo GitHub đầu tiên", isProject: true },
      { label: "Tuần 3-4", focus: "Functions, files, testing + Toán", course: "CS50P, Khan Academy", milestone: "Mini CSV parser + notebook xác suất" },
      { label: "Tuần 5-6", focus: "Thống kê suy luận + SQL", course: "OpenIntro, PostgreSQL", milestone: "25 bài SQL + writeup kiểm định" },
      { label: "Tuần 7-8", focus: "SQL nâng cao + pandas", course: "UC Davis SQL, Kaggle", milestone: "Project 1: Dashboard", isProject: true },
      { label: "Tuần 9-10", focus: "Cleaning, EDA, Visualization", course: "pandas docs, Kaggle Viz", milestone: "Project 2: Sales Analytics", isProject: true },
      { label: "Tuần 11-12", focus: "Regression + Classification", course: "Google MLCC, Andrew Ng", milestone: "Notebook dự đoán + confusion matrix" },
      { label: "Tuần 13-14", focus: "Trees, ensembles, đánh giá", course: "scikit-learn, MLCC", milestone: "Bảng so sánh ≥3 mô hình" },
      { label: "Tuần 15-16", focus: "Pipelines + Unsupervised", course: "scikit-learn, Kaggle", milestone: "Project 3: Segmentation", isProject: true },
      { label: "Tuần 17-18", focus: "Time series + Responsible AI", course: "Kaggle TS, NIST", milestone: "Project 4: Churn Prediction", isProject: true, isCapstone: true },
      { label: "Tuần 19-20", focus: "Deep Learning cơ bản", course: "PyTorch, fast.ai", milestone: "Train 1 NN đơn giản" },
      { label: "Tuần 21-22", focus: "MLOps + FastAPI + Docker", course: "FastAPI, Docker, MLflow", milestone: "Project 5: ML API Service", isProject: true },
      { label: "Tuần 23-24", focus: "Cloud + LLM/RAG + Phỏng vấn", course: "DeepLearning.AI, Streamlit", milestone: "Project 6: RAG App + Mock interview", isProject: true, isCapstone: true },
    ],
  },
  {
    id: "9",
    months: 9,
    title: "Tiêu Chuẩn",
    audience: "Hầu hết người mới — cân bằng nhất, đủ thời gian xây portfolio thật",
    hoursPerWeek: "10-12 giờ/tuần",
    totalHours: "~360-430 giờ",
    recommended: true,
    rows: [
      { label: "Tháng 1", focus: "Python, Git, study system", course: "CS50P, Pro Git", milestone: "Repo đầu + coding drills" },
      { label: "Tháng 2", focus: "Toán: đại số, xác suất, thống kê", course: "Khan Academy, OpenIntro", milestone: "Simulation notebook + EDA memo" },
      { label: "Tháng 3", focus: "SQL: basics → window/CTE", course: "PostgreSQL, UC Davis SQL", milestone: "Tái tạo business metric" },
      { label: "Tháng 4", focus: "pandas, cleaning, reshape, viz", course: "Kaggle Pandas, Matplotlib", milestone: "Project 1: Dashboard", isProject: true },
      { label: "Tháng 5", focus: "Regression, classification, trees", course: "Google MLCC, Andrew Ng", milestone: "Project 2: Sales Analytics", isProject: true },
      { label: "Tháng 6", focus: "Evaluation, pipelines, unsupervised, TS", course: "scikit-learn, Kaggle", milestone: "Project 3: Segmentation + Project 4: Churn", isProject: true, isCapstone: true },
      { label: "Tháng 7", focus: "Deep Learning + embeddings", course: "fast.ai, PyTorch, DLAI", milestone: "Train NN + bài tập embedding" },
      { label: "Tháng 8", focus: "MLOps: MLflow, DVC, FastAPI, Docker", course: "FastAPI, Docker, MLflow", milestone: "Project 5: ML API Service", isProject: true },
      { label: "Tháng 9", focus: "Cloud + LLM/RAG + hiring prep", course: "Google Skills, DeepLearning.AI", milestone: "Project 6: RAG App + Mock interview + CV", isProject: true, isCapstone: true },
    ],
  },
  {
    id: "12",
    months: 12,
    title: "Thong Thả",
    audience: "Người đi làm full-time, bận rộn — bền vững, ít kiệt sức",
    hoursPerWeek: "7-9 giờ/tuần",
    totalHours: "~340-430 giờ",
    rows: [
      { label: "Tháng 1-2", focus: "Python + Git + Toán cơ bản", course: "CS50P, Khan Academy", milestone: "Repo đầu + simulation notebook" },
      { label: "Tháng 3", focus: "Thống kê mô tả & suy luận", course: "OpenIntro", milestone: "EDA memo + writeup kiểm định" },
      { label: "Tháng 4", focus: "SQL từ cơ bản → window/CTE", course: "PostgreSQL, UC Davis", milestone: "Tái tạo business metric" },
      { label: "Tháng 5", focus: "pandas, cleaning, reshape", course: "Kaggle Pandas", milestone: "'Messy data cleanup' notebook" },
      { label: "Tháng 6", focus: "Viz + storytelling", course: "Matplotlib, Seaborn", milestone: "Project 1 + 2: Dashboards", isProject: true },
      { label: "Tháng 7", focus: "Regression, classification, trees", course: "Google MLCC, Andrew Ng", milestone: "Confusion matrix + so sánh mô hình" },
      { label: "Tháng 8", focus: "Evaluation, pipeline, feature work", course: "scikit-learn", milestone: "Project 3: Segmentation", isProject: true },
      { label: "Tháng 9", focus: "Unsupervised, TS, Responsible AI", course: "Kaggle, NIST", milestone: "Project 4: Churn", isProject: true, isCapstone: true },
      { label: "Tháng 10", focus: "NN intuition + PyTorch + embeddings", course: "fast.ai, PyTorch", milestone: "Train NN + bài tập embedding" },
      { label: "Tháng 11", focus: "MLflow, DVC, FastAPI, Docker", course: "FastAPI, Docker, Streamlit", milestone: "Project 5: ML API Service", isProject: true },
      { label: "Tháng 12", focus: "Cloud + LLM/RAG/Agent + Phỏng vấn", course: "DeepLearning.AI, LangGraph", milestone: "Project 6: RAG App + CV + Mock interview", isProject: true, isCapstone: true },
    ],
  },
];
