import type { Plan } from "./types";

export const PLANS: Plan[] = [
  {
    id: "6",
    months: 6,
    title: "Accelerated",
    audience: "Career changers with protected study time",
    hoursPerWeek: "15-18 hrs/week",
    totalHours: "~360-430 hrs",
    rows: [
      { label: "Weeks 1-2", focus: "Setup, Python basics, Git", course: "CS50P, Python Tutorial", milestone: "First GitHub repo", isProject: true },
      { label: "Weeks 3-4", focus: "Functions, files, testing + Math", course: "CS50P, Khan Academy", milestone: "Mini CSV parser + probability notebook" },
      { label: "Weeks 5-6", focus: "Inferential stats + SQL", course: "OpenIntro, PostgreSQL", milestone: "25 SQL exercises + test writeup" },
      { label: "Weeks 7-8", focus: "Advanced SQL + pandas", course: "UC Davis SQL, Kaggle", milestone: "Project 1: Dashboard", isProject: true },
      { label: "Weeks 9-10", focus: "Cleaning, EDA, Visualization", course: "pandas docs, Kaggle Viz", milestone: "Project 2: Sales Analytics", isProject: true },
      { label: "Weeks 11-12", focus: "Regression + Classification", course: "Google MLCC, Andrew Ng", milestone: "Prediction notebook + confusion matrix" },
      { label: "Weeks 13-14", focus: "Trees, ensembles, evaluation", course: "scikit-learn, MLCC", milestone: "3+ model comparison table" },
      { label: "Weeks 15-16", focus: "Pipelines + Unsupervised", course: "scikit-learn, Kaggle", milestone: "Project 3: Segmentation", isProject: true },
      { label: "Weeks 17-18", focus: "Time series + Responsible AI", course: "Kaggle TS, NIST", milestone: "Project 4: Churn Prediction", isProject: true, isCapstone: true },
      { label: "Weeks 19-20", focus: "Deep Learning basics", course: "PyTorch, fast.ai", milestone: "Train a simple NN" },
      { label: "Weeks 21-22", focus: "MLOps + FastAPI + Docker", course: "FastAPI, Docker, MLflow", milestone: "Project 5: ML API Service", isProject: true },
      { label: "Weeks 23-24", focus: "Cloud + LLM/RAG + interview prep", course: "DeepLearning.AI, Streamlit", milestone: "Project 6: RAG App + mock interview", isProject: true, isCapstone: true },
    ],
  },
  {
    id: "9",
    months: 9,
    title: "Standard",
    audience: "Most beginners — the most balanced, enough time to build a real portfolio",
    hoursPerWeek: "10-12 hrs/week",
    totalHours: "~360-430 hrs",
    recommended: true,
    rows: [
      { label: "Month 1", focus: "Python, Git, study system", course: "CS50P, Pro Git", milestone: "First repo + coding drills" },
      { label: "Month 2", focus: "Math: algebra, probability, stats", course: "Khan Academy, OpenIntro", milestone: "Simulation notebook + EDA memo" },
      { label: "Month 3", focus: "SQL: basics → window/CTE", course: "PostgreSQL, UC Davis SQL", milestone: "Reproduce a business metric" },
      { label: "Month 4", focus: "pandas, cleaning, reshape, viz", course: "Kaggle Pandas, Matplotlib", milestone: "Project 1: Dashboard", isProject: true },
      { label: "Month 5", focus: "Regression, classification, trees", course: "Google MLCC, Andrew Ng", milestone: "Project 2: Sales Analytics", isProject: true },
      { label: "Month 6", focus: "Evaluation, pipelines, unsupervised, TS", course: "scikit-learn, Kaggle", milestone: "Project 3: Segmentation + Project 4: Churn", isProject: true, isCapstone: true },
      { label: "Month 7", focus: "Deep Learning + embeddings", course: "fast.ai, PyTorch, DLAI", milestone: "Train NN + embedding exercise" },
      { label: "Month 8", focus: "MLOps: MLflow, DVC, FastAPI, Docker", course: "FastAPI, Docker, MLflow", milestone: "Project 5: ML API Service", isProject: true },
      { label: "Month 9", focus: "Cloud + LLM/RAG + hiring prep", course: "Google Skills, DeepLearning.AI", milestone: "Project 6: RAG App + mock interview + CV", isProject: true, isCapstone: true },
    ],
  },
  {
    id: "12",
    months: 12,
    title: "Relaxed",
    audience: "Busy full-time workers — sustainable, lower burnout",
    hoursPerWeek: "7-9 hrs/week",
    totalHours: "~340-430 hrs",
    rows: [
      { label: "Months 1-2", focus: "Python + Git + basic math", course: "CS50P, Khan Academy", milestone: "First repo + simulation notebook" },
      { label: "Month 3", focus: "Descriptive & inferential stats", course: "OpenIntro", milestone: "EDA memo + test writeup" },
      { label: "Month 4", focus: "SQL from basics → window/CTE", course: "PostgreSQL, UC Davis", milestone: "Reproduce a business metric" },
      { label: "Month 5", focus: "pandas, cleaning, reshape", course: "Kaggle Pandas", milestone: "'Messy data cleanup' notebook" },
      { label: "Month 6", focus: "Viz + storytelling", course: "Matplotlib, Seaborn", milestone: "Project 1 + 2: Dashboards", isProject: true },
      { label: "Month 7", focus: "Regression, classification, trees", course: "Google MLCC, Andrew Ng", milestone: "Confusion matrix + model comparison" },
      { label: "Month 8", focus: "Evaluation, pipeline, feature work", course: "scikit-learn", milestone: "Project 3: Segmentation", isProject: true },
      { label: "Month 9", focus: "Unsupervised, TS, Responsible AI", course: "Kaggle, NIST", milestone: "Project 4: Churn", isProject: true, isCapstone: true },
      { label: "Month 10", focus: "NN intuition + PyTorch + embeddings", course: "fast.ai, PyTorch", milestone: "Train NN + embedding exercise" },
      { label: "Month 11", focus: "MLflow, DVC, FastAPI, Docker", course: "FastAPI, Docker, Streamlit", milestone: "Project 5: ML API Service", isProject: true },
      { label: "Month 12", focus: "Cloud + LLM/RAG/Agent + interview", course: "DeepLearning.AI, LangGraph", milestone: "Project 6: RAG App + CV + mock interview", isProject: true, isCapstone: true },
    ],
  },
];
